// The OSD's own sentences.
//
// The Rust side never sends one: it sends a code and a reason, and this file is
// where a code becomes something a person reads. That is decision 25 applied to
// the player -- the same rule that keeps Windows syscall names out of a French
// settings page.
//
// English is the default, French ships complete, and the two catalogues are
// expected to grow together. A parity check belongs here the moment this file
// carries more than a screenful; the web application's own check is
// web/scripts/check-locales.mjs.
//
// `vocabulary` is the other half of the same job: the words a *label* is built
// from rather than sentences -- a language name, a channel layout, the readable
// name of a codec. It is a map of maps because `catalogues` is flat and
// `scripts/check-locales.mjs` asserts every value in it is a sentence, which a
// language name is not.

export const catalogues = {
	fr: {
		play: 'Lecture',
		pause: 'Pause',
		back10: 'Reculer de 10 secondes',
		forward10: 'Avancer de 10 secondes',
		mute: 'Couper le son',
		unmute: 'Rétablir le son',
		volume: 'Volume',
		fullscreen: 'Plein écran',
		exitFullscreen: 'Quitter le plein écran',
		close: 'Fermer le lecteur',
		minimize: 'Réduire la fenêtre',
		maximize: 'Agrandir la fenêtre',
		restore: 'Restaurer la fenêtre',
		backToLibrary: 'Retour à la bibliothèque',
		tracks: 'Audio et sous-titres',
		loading: 'Chargement',
		engineUnavailable:
			"Le moteur de lecture n'a pas pu démarrer. Le lecteur ne peut pas ouvrir de film.",
		engineUnavailableLabel: 'Lecture',
		audioFallbackLabel: 'Son',
		audioFallback:
			"Le convertisseur HDMI a refusé le flux audio brut : le film est lu en PCM décodé. Rien n'est cassé, mais le son n'arrive pas tel quel à l'amplificateur.",
		chooseFilm: 'Choisir un film',

		// The home screen. Row titles mirror the web application's word for
		// word: one product, one vocabulary. `remainingPattern` carries the
		// sentence with a {d} the code replaces, because French leads with "Il
		// reste" and English trails with "left".
		home: 'Accueil',
		heroResumeEyebrow: 'Vous étiez en train de regarder',
		heroFeaturedEyebrow: "À l'affiche",
		resume: 'Reprendre',
		remainingPattern: 'Il reste {d}',
		ratingScale: '/ 10',
		rowContinue: 'Continuer à regarder',
		rowRecent: 'Récemment ajoutés',
		rowTopRated: 'Les mieux notés',
		rowTonight: 'Au hasard ce soir',
		rowTonightHint: 'Une sélection qui change chaque jour',
		rowSeriesContinue: 'Reprendre une série',
		rowSeriesRecent: 'Séries récemment ajoutées',
		scrollLeft: 'Faire défiler vers la gauche',
		scrollRight: 'Faire défiler vers la droite',
		homeFailed: "L'accueil n'a pas pu être chargé.",

		connectTitle: 'Connexion à Theia',
		starting: 'Démarrage de Theia',
		startingHint: 'Le serveur et la bibliothèque se préparent…',
		library: 'Bibliothèque',
		libraryNavigation: 'Navigation de la bibliothèque',
		desktopPlayer: 'Application de lecture',
		yourLibrary: 'Votre bibliothèque',
		films: 'Films',
		allFilms: 'Tous les films',
		series: 'Séries',
		search: 'Rechercher',
		searchTitle: 'Recherche',
		searchPlaceholder: 'Un film, une série, une année…',
		searchHint: 'Commence à écrire pour explorer toute la bibliothèque.',
		noSearchResults: 'Aucun titre ne correspond à cette recherche.',
		filmResults: 'Films',
		seriesResults: 'Séries',
		seriesLabel: 'Série',
		allSeries: 'Toutes les séries',
		seasons: 'Saisons',
		season: 'Saison',
		filmSingular: 'film',
		filmPlural: 'films',
		seriesSingular: 'série',
		seriesPlural: 'séries',
		// The counts on a series card, lowercase because they sit inside a
		// legend. Four words rather than a formatter: the cards ask for the one
		// that matches the number they are about to print.
		seasonSingular: 'saison',
		seasonPlural: 'saisons',
		episodeSingular: 'épisode',
		episodePlural: 'épisodes',
		connected: 'Connecté',
		playMovie: 'Lire le film',
		openSeries: 'Ouvrir la série',
		playEpisode: "Lire l'épisode",
		episodeUntitled: 'Épisode',
		address: 'Adresse du serveur',
		connect: 'Se connecter',
		findServers: 'Chercher un serveur',
		searching: 'Recherche…',
		noServer:
			"Aucun serveur détecté sur le réseau. Saisis l'adresse que Theia affiche à son démarrage.",
		connectionFailed: "La connexion a échoué. Vérifie l'adresse, et que Theia est bien démarré.",
		libraryFailed: "La bibliothèque n'a pas pu être chargée.",
		seriesFailed: "Cette série n'a pas pu être chargée.",
		episodeFailed: "Cet épisode n'a pas pu être ouvert.",
		playFailed: "Ce film n'a pas pu être ouvert.",
		stopFailed: "Le film n'a pas pu être fermé proprement.",
		emptyLibrary: 'Cette bibliothèque ne contient encore aucun film.',
		emptySeries: 'Cette bibliothèque ne contient encore aucune série.',
		emptySeason: 'Cette saison ne contient aucun épisode lisible.',
		resumeAt: 'Reprendre à',
		audioTracks: 'Piste audio',
		subtitleTracks: 'Sous-titres',
		subtitlesOff: 'Aucun',
		qualityTab: 'Qualité',
		languagesTab: 'Langues',
		qualityOriginal: 'Qualité du fichier',
		trackFailed: "Cette piste n'a pas pu être choisie.",
		settings: 'Réglages',
		profiles: 'Profils',
		profileDescription: 'Choisis qui regarde. La bibliothèque et la progression suivent ce profil.',
		closeProfiles: 'Fermer les profils',
		profileDefaultName: 'Profil principal',
		currentProfile: 'Profil actuel',
		switchProfile: 'Utiliser ce profil',
		noProfiles: 'Aucun profil disponible sur ce serveur.',
		profileSwitchFailed: "Le profil n'a pas pu être sélectionné.",
		personalizeProfile: 'Personnaliser le profil',
		personalizeProfileDescription: 'Change son nom et sa photo sans toucher à sa progression.',
		profileName: 'Nom du profil',
		changePicture: 'Changer la photo',
		removePicture: 'Retirer la photo',
		profilePictureHint: 'PNG, JPEG ou WebP. Theia recadre et optimise automatiquement la photo.',
		profileSaveFailed: "Le profil n'a pas pu être enregistré.",
		savingProfile: 'Enregistrement…',
		saveProfile: 'Enregistrer le profil',
		back: 'Retour',
		settingsDescription: 'Préférences de cette application de lecture.',
		closeSettings: 'Fermer les réglages',
		interface: 'Interface',
		playback: 'Lecture',
		playbackHint: 'Comment le lecteur se comporte pendant un film.',
		settingsSections: 'Sections des réglages',
		language: 'Langue',
		languageHint: "Change uniquement la langue de l'application desktop.",
		autoHideControls: 'Masquer les contrôles',
		autoHideControlsHint: 'Fait disparaître le mobilier après trois secondes pendant la lecture.',
		reducedMotion: 'Réduire les animations',
		reducedMotionHint: 'Supprime les déplacements sans retirer les changements d’état utiles.',
		server: 'Serveur',
		serverConnectedHint: 'Connexion locale active. Le player se reconnecte automatiquement au prochain lancement.',
		serverDisconnectedHint: "Aucun serveur n'est connecté.",
		copyAddress: "Copier l'adresse du serveur",
		addressCopied: 'Adresse copiée.',
		addressCopyFailed: "L'adresse n'a pas pu être copiée.",
		version: 'Version',
		update: 'Mise à jour',
		updateCurrent: 'Actuelle',
		updateLatest: 'Disponible',
		updateCheck: 'Vérifier',
		updateChecking: 'Vérification…',
		updateInstall: 'Installer la mise à jour',
		updateInstalling: 'Installation…',
		updateAvailable: 'Mise à jour disponible',
		updateReady: 'Mise à jour prête. Redémarre Theia pour terminer.',
		updateDeferred: 'La mise à jour attend que la lecture soit terminée.',
		updateFailed: "La mise à jour a échoué. Tu peux relancer la vérification.",
		updateUnsupported: "Les mises à jour automatiques ne sont pas disponibles sur cette installation.",
		updateUnknown: "Aucune vérification récente. Lance-en une maintenant.",
		cancel: 'Annuler',
		save: 'Enregistrer',
	},
	en: {
		play: 'Play',
		pause: 'Pause',
		back10: 'Back 10 seconds',
		forward10: 'Forward 10 seconds',
		mute: 'Mute',
		unmute: 'Unmute',
		volume: 'Volume',
		fullscreen: 'Full screen',
		exitFullscreen: 'Leave full screen',
		close: 'Close the player',
		minimize: 'Minimize the window',
		maximize: 'Maximize the window',
		restore: 'Restore the window',
		backToLibrary: 'Back to the library',
		tracks: 'Audio and subtitles',
		loading: 'Loading',
		engineUnavailable: 'The playback engine could not start, so no film can be opened.',
		engineUnavailableLabel: 'Playback',
		audioFallbackLabel: 'Sound',
		audioFallback:
			'The HDMI endpoint refused the raw audio stream, so the film is playing as decoded PCM. Nothing is broken, but the sound is not reaching the amplifier untouched.',

		chooseFilm: 'Choose a film',

		// The home screen - see the French catalogue's note on the {d}.
		home: 'Home',
		heroResumeEyebrow: 'You were watching',
		heroFeaturedEyebrow: 'Now showing',
		resume: 'Resume',
		remainingPattern: '{d} left',
		ratingScale: '/ 10',
		rowContinue: 'Continue watching',
		rowRecent: 'Recently added',
		rowTopRated: 'Top rated',
		rowTonight: 'Tonight’s random picks',
		rowTonightHint: 'A selection that changes every day',
		rowSeriesContinue: 'Continue a series',
		rowSeriesRecent: 'Recently added series',
		scrollLeft: 'Scroll left',
		scrollRight: 'Scroll right',
		homeFailed: 'The home screen could not be loaded.',

		connectTitle: 'Connect to Theia',
		starting: 'Starting Theia',
		startingHint: 'The server and library are getting ready…',
		library: 'Library',
		libraryNavigation: 'Library navigation',
		desktopPlayer: 'Desktop player',
		yourLibrary: 'Your library',
		films: 'Movies',
		allFilms: 'All movies',
		series: 'Series',
		search: 'Search',
		searchTitle: 'Search',
		searchPlaceholder: 'A movie, a series, a year…',
		searchHint: 'Start typing to explore the whole library.',
		noSearchResults: 'No title matches this search.',
		filmResults: 'Movies',
		seriesResults: 'Series',
		seriesLabel: 'Series',
		allSeries: 'All series',
		seasons: 'Seasons',
		season: 'Season',
		filmSingular: 'movie',
		filmPlural: 'movies',
		seriesSingular: 'series',
		seriesPlural: 'series',
		seasonSingular: 'season',
		seasonPlural: 'seasons',
		episodeSingular: 'episode',
		episodePlural: 'episodes',
		connected: 'Connected',
		playMovie: 'Play movie',
		openSeries: 'Open series',
		playEpisode: 'Play episode',
		episodeUntitled: 'Episode',
		address: 'Server address',
		connect: 'Connect',
		findServers: 'Find a server',
		searching: 'Searching…',
		noServer: 'No server answered on the network. Enter the address Theia prints when it starts.',
		connectionFailed: 'The connection failed. Check the address, and that Theia is running.',
		libraryFailed: 'The library could not be loaded.',
		seriesFailed: 'That series could not be loaded.',
		episodeFailed: 'That episode could not be opened.',
		playFailed: 'This film could not be opened.',
		stopFailed: 'The film could not be closed cleanly.',
		emptyLibrary: 'This library holds no films yet.',
		emptySeries: 'This library holds no series yet.',
		emptySeason: 'This season has no playable episode.',
		resumeAt: 'Resume at',
		audioTracks: 'Audio track',
		subtitleTracks: 'Subtitles',
		subtitlesOff: 'None',
		qualityTab: 'Quality',
		languagesTab: 'Languages',
		qualityOriginal: 'As the file is',
		trackFailed: 'That track could not be selected.',
		settings: 'Settings',
		profiles: 'Profiles',
		profileDescription: 'Choose who is watching. Library state and progress follow this profile.',
		closeProfiles: 'Close profiles',
		profileDefaultName: 'Main profile',
		currentProfile: 'Current profile',
		switchProfile: 'Use this profile',
		noProfiles: 'No profile is available on this server.',
		profileSwitchFailed: 'That profile could not be selected.',
		personalizeProfile: 'Customize profile',
		personalizeProfileDescription: 'Change its name and picture without touching its progress.',
		profileName: 'Profile name',
		changePicture: 'Change picture',
		removePicture: 'Remove picture',
		profilePictureHint: 'PNG, JPEG or WebP. Theia crops and optimizes the picture automatically.',
		profileSaveFailed: 'The profile could not be saved.',
		savingProfile: 'Saving…',
		saveProfile: 'Save profile',
		back: 'Back',
		settingsDescription: 'Preferences for this desktop player.',
		closeSettings: 'Close settings',
		interface: 'Interface',
		playback: 'Playback',
		playbackHint: 'How the player behaves while a film is playing.',
		settingsSections: 'Settings sections',
		language: 'Language',
		languageHint: 'Changes the language of this desktop app only.',
		autoHideControls: 'Hide controls',
		autoHideControlsHint: 'Hides the furniture after three seconds during playback.',
		reducedMotion: 'Reduce motion',
		reducedMotionHint: 'Removes movement without hiding useful state changes.',
		server: 'Server',
		serverConnectedHint: 'Local connection active. The player reconnects automatically next time.',
		serverDisconnectedHint: 'No server is connected.',
		copyAddress: 'Copy the server address',
		addressCopied: 'Address copied.',
		addressCopyFailed: 'The address could not be copied.',
		version: 'Version',
		update: 'Update',
		updateCurrent: 'Current',
		updateLatest: 'Available',
		updateCheck: 'Check',
		updateChecking: 'Checking…',
		updateInstall: 'Install update',
		updateInstalling: 'Installing…',
		updateAvailable: 'Update available',
		updateReady: 'Update ready. Restart Theia to finish.',
		updateDeferred: 'The update is waiting for playback to finish.',
		updateFailed: 'The update failed. You can run the check again.',
		updateUnsupported: 'Automatic updates are not available for this installation.',
		updateUnknown: 'No recent check. Run one now.',
		cancel: 'Cancel',
		save: 'Save',
	},
};

/** The words a track's label is built from, per language.
 *
 * The language names mirror the web application's own map, code for code, so a
 * track is called the same thing in both players; the channel words follow the
 * same rule ffmpeg does -- it writes "stereo" and "mono", and everything else
 * (5.1, 7.1, 3.0) already reads as itself. `channelCount` carries an {n} because
 * a container that writes no layout leaves only the number of channels, and
 * "6 canaux" is the honest thing to say about one. */
export const vocabulary = {
	fr: {
		languages: {
			fra: 'Français', fre: 'Français', fr: 'Français',
			eng: 'Anglais', en: 'Anglais',
			spa: 'Espagnol', es: 'Espagnol',
			deu: 'Allemand', ger: 'Allemand', de: 'Allemand',
			ita: 'Italien', it: 'Italien',
			por: 'Portugais', pt: 'Portugais',
			nld: 'Néerlandais', dut: 'Néerlandais', nl: 'Néerlandais',
			jpn: 'Japonais', ja: 'Japonais',
			zho: 'Chinois', chi: 'Chinois', zh: 'Chinois',
			kor: 'Coréen', ko: 'Coréen',
			rus: 'Russe', ru: 'Russe',
			ara: 'Arabe', ar: 'Arabe',
			pol: 'Polonais', pl: 'Polonais',
			swe: 'Suédois', sv: 'Suédois',
			dan: 'Danois', da: 'Danois',
			nor: 'Norvégien', no: 'Norvégien',
			fin: 'Finnois', fi: 'Finnois',
			tur: 'Turc', tr: 'Turc',
			ces: 'Tchèque', cze: 'Tchèque', cs: 'Tchèque',
			ell: 'Grec', gre: 'Grec', el: 'Grec',
			heb: 'Hébreu', he: 'Hébreu',
			hin: 'Hindi', hi: 'Hindi',
			und: 'Langue non précisée', mul: 'Multilingue',
		},
		channels: { mono: 'Mono', stereo: 'Stéréo' },
		channelCount: '{n} canaux',
		commentary: 'Commentaire',
		forced: 'Forcés',
		external: 'fichier joint',
		unnamedAudio: 'Piste {n}',
		unnamedSubtitle: 'Sous-titres {n}',
		qualityHeight: '{n}p',
		qualityReencoded: 'réencodée',
		qualityHardware: 'carte graphique',
		qualitySoftware: 'processeur',
		codecs: {
			ac3: 'AC-3', eac3: 'E-AC-3', dts: 'DTS', truehd: 'TrueHD', mlp: 'MLP',
			pcm: 'PCM', aac: 'AAC', flac: 'FLAC', alac: 'ALAC', opus: 'Opus', vorbis: 'Vorbis',
			mp3: 'MP3', mp2: 'MP2', wmav2: 'WMA', wmapro: 'WMA Pro',
			subrip: 'SubRip', ass: 'ASS', ssa: 'SSA', webvtt: 'WebVTT',
			hdmv_pgs_subtitle: 'PGS', dvd_subtitle: 'VobSub', dvdsub: 'VobSub',
			mov_text: 'Texte', ttml: 'TTML', dvb_subtitle: 'DVB',
		},
	},
	en: {
		languages: {
			fra: 'French', fre: 'French', fr: 'French',
			eng: 'English', en: 'English',
			spa: 'Spanish', es: 'Spanish',
			deu: 'German', ger: 'German', de: 'German',
			ita: 'Italian', it: 'Italian',
			por: 'Portuguese', pt: 'Portuguese',
			nld: 'Dutch', dut: 'Dutch', nl: 'Dutch',
			jpn: 'Japanese', ja: 'Japanese',
			zho: 'Chinese', chi: 'Chinese', zh: 'Chinese',
			kor: 'Korean', ko: 'Korean',
			rus: 'Russian', ru: 'Russian',
			ara: 'Arabic', ar: 'Arabic',
			pol: 'Polish', pl: 'Polish',
			swe: 'Swedish', sv: 'Swedish',
			dan: 'Danish', da: 'Danish',
			nor: 'Norwegian', no: 'Norwegian',
			fin: 'Finnish', fi: 'Finnish',
			tur: 'Turkish', tr: 'Turkish',
			ces: 'Czech', cze: 'Czech', cs: 'Czech',
			ell: 'Greek', gre: 'Greek', el: 'Greek',
			heb: 'Hebrew', he: 'Hebrew',
			hin: 'Hindi', hi: 'Hindi',
			und: 'Language not stated', mul: 'Multiple languages',
		},
		channels: { mono: 'Mono', stereo: 'Stereo' },
		channelCount: '{n} channels',
		commentary: 'Commentary',
		forced: 'Forced',
		external: 'external file',
		unnamedAudio: 'Track {n}',
		unnamedSubtitle: 'Subtitle {n}',
		qualityHeight: '{n}p',
		qualityReencoded: 're-encoded',
		qualityHardware: 'graphics card',
		qualitySoftware: 'processor',
		codecs: {
			ac3: 'AC-3', eac3: 'E-AC-3', dts: 'DTS', truehd: 'TrueHD', mlp: 'MLP',
			pcm: 'PCM', aac: 'AAC', flac: 'FLAC', alac: 'ALAC', opus: 'Opus', vorbis: 'Vorbis',
			mp3: 'MP3', mp2: 'MP2', wmav2: 'WMA', wmapro: 'WMA Pro',
			subrip: 'SubRip', ass: 'ASS', ssa: 'SSA', webvtt: 'WebVTT',
			hdmv_pgs_subtitle: 'PGS', dvd_subtitle: 'VobSub', dvdsub: 'VobSub',
			mov_text: 'Text', ttml: 'TTML', dvb_subtitle: 'DVB',
		},
	},
};

/** The vocabulary for a language, English when the code is not one of ours --
 * the same rule `initialLanguage` follows, because an unknown code must not be
 * able to empty a menu. */
export function trackVocabulary(language) {
	return vocabulary[language] ?? vocabulary.en;
}

/** The language this machine's viewer chose here, or null when nobody has.
 *
 * Kept apart from the language to open in, because the two answer different
 * questions: this one says whether the server's preference still has a say. */
export function storedLanguage() {
	try {
		const stored = localStorage.getItem('theia.player.language');
		if (stored && catalogues[stored]) return stored;
	} catch {
		// A WebView with storage disabled has no memory to read.
	}
	return null;
}

/** The interface language to open in: the stored choice wins, then the language
 * the installation was set up in arrives from the server (see App's connect),
 * and English is the base of the product — the player opens in English on every
 * machine until somebody picks another language, French systems included. */
export function initialLanguage() {
	return storedLanguage() ?? 'en';
}
