// The OSD's own sentences.
//
// The Rust side never sends one: it sends a code and a reason, and this file is
// where a code becomes something a person reads. That is decision 25 applied to
// the player -- the same rule that keeps Windows syscall names out of a French
// settings page.
//
// English is the default, French ships complete, and the two catalogues are
// expected to grow together. A parity check belongs here the moment this file
// carries more than a screenful; the web application's own check is
// web/scripts/check-locales.mjs.
//
// `vocabulary` is the other half of the same job: the words a *label* is built
// from rather than sentences -- a language name, a channel layout, the readable
// name of a codec. It is a map of maps because `catalogues` is flat and
// `scripts/check-locales.mjs` asserts every value in it is a sentence, which a
// language name is not.

export const catalogues = {
	fr: {
		play: 'Lecture',
		pause: 'Pause',
		back10: 'Reculer de 10 secondes',
		forward10: 'Avancer de 10 secondes',
		mute: 'Couper le son',
		unmute: 'Rétablir le son',
		volume: 'Volume',
		fullscreen: 'Plein écran',
		exitFullscreen: 'Quitter le plein écran',
		close: 'Fermer le lecteur',
		minimize: 'Réduire la fenêtre',
		maximize: 'Agrandir la fenêtre',
		restore: 'Restaurer la fenêtre',
		backToLibrary: 'Retour à la bibliothèque',
		tracks: 'Audio et sous-titres',
		loading: 'Chargement',
		engineUnavailable:
			"Le moteur de lecture n'a pas pu démarrer. Le lecteur ne peut pas ouvrir de film.",
		engineUnavailableLabel: 'Lecture',
		audioFallbackLabel: 'Son',
		audioFallback:
			"Le convertisseur HDMI a refusé le flux audio brut : le film est lu en PCM décodé. Rien n'est cassé, mais le son n'arrive pas tel quel à l'amplificateur.",
		chooseFilm: 'Choisir un film',

		// The home screen. Row titles mirror the web application's word for
		// word: one product, one vocabulary. `remainingPattern` carries the
		// sentence with a {d} the code replaces, because French leads with "Il
		// reste" and English trails with "left".
		home: 'Accueil',
		heroResumeEyebrow: 'Vous étiez en train de regarder',
		heroFeaturedEyebrow: "À l'affiche",
		resume: 'Reprendre',
		remainingPattern: 'Il reste {d}',
		ratingScale: '/ 10',
		rowContinue: 'Continuer à regarder',
		rowRecent: 'Récemment ajoutés',
		rowTopRated: 'Les mieux notés',
		rowTonight: 'Au hasard ce soir',
		rowTonightHint: 'Une sélection qui change chaque jour',
		rowSeriesContinue: 'Reprendre une série',
		rowSeriesRecent: 'Séries récemment ajoutées',
		scrollLeft: 'Faire défiler vers la gauche',
		scrollRight: 'Faire défiler vers la droite',
		homeFailed: "L'accueil n'a pas pu être chargé.",

		connectTitle: 'Connexion à Theia',
		starting: 'Démarrage de Theia',
		startingHint: 'Le serveur et la bibliothèque se préparent…',
		library: 'Bibliothèque',
		libraryNavigation: 'Navigation de la bibliothèque',
		desktopPlayer: 'Application de lecture',
		yourLibrary: 'Votre bibliothèque',
		films: 'Films',
		allFilms: 'Tous les films',
		series: 'Séries',
		search: 'Rechercher',
		searchTitle: 'Recherche',
		searchPlaceholder: 'Un film, une série, une année…',
		searchHint: 'Commence à écrire pour explorer toute la bibliothèque.',
		noSearchResults: 'Aucun titre ne correspond à cette recherche.',
		filmResults: 'Films',
		seriesResults: 'Séries',
		seriesLabel: 'Série',
		allSeries: 'Toutes les séries',
		seasons: 'Saisons',
		season: 'Saison',
		filmSingular: 'film',
		filmPlural: 'films',
		seriesSingular: 'série',
		seriesPlural: 'séries',
		// The counts on a series card, lowercase because they sit inside a
		// legend. Four words rather than a formatter: the cards ask for the one
		// that matches the number they are about to print.
		seasonSingular: 'saison',
		seasonPlural: 'saisons',
		episodeSingular: 'épisode',
		episodePlural: 'épisodes',
		connected: 'Connecté',
		playMovie: 'Lire le film',
		openSeries: 'Ouvrir la série',
		playEpisode: "Lire l'épisode",
		episodeUntitled: 'Épisode',
		address: 'Adresse du serveur',
		connect: 'Se connecter',
		findServers: 'Chercher un serveur',
		searching: 'Recherche…',
		noServer:
			"Aucun serveur détecté sur le réseau. Saisis l'adresse que Theia affiche à son démarrage.",
		connectionFailed: "La connexion a échoué. Vérifie l'adresse, et que Theia est bien démarré.",
		libraryFailed: "La bibliothèque n'a pas pu être chargée.",
		seriesFailed: "Cette série n'a pas pu être chargée.",
		episodeFailed: "Cet épisode n'a pas pu être ouvert.",
		playFailed: "Ce film n'a pas pu être ouvert.",
		stopFailed: "Le film n'a pas pu être fermé proprement.",
		emptyLibrary: 'Cette bibliothèque ne contient encore aucun film.',
		emptySeries: 'Cette bibliothèque ne contient encore aucune série.',
		emptySeason: 'Cette saison ne contient aucun épisode lisible.',
		resumeAt: 'Reprendre à',
		audioTracks: 'Piste audio',
		subtitleTracks: 'Sous-titres',
		subtitlesOff: 'Aucun',
		qualityTab: 'Qualité',
		languagesTab: 'Langues',
		qualityOriginal: 'Qualité du fichier',
		trackFailed: "Cette piste n'a pas pu être choisie.",
		settings: 'Réglages',
		profiles: 'Profils',
		profileDescription: 'Choisis qui regarde. La bibliothèque et la progression suivent ce profil.',
		closeProfiles: 'Fermer les profils',
		profileDefaultName: 'Profil principal',
		currentProfile: 'Profil actuel',
		switchProfile: 'Utiliser ce profil',
		noProfiles: 'Aucun profil disponible sur ce serveur.',
		profileSwitchFailed: "Le profil n'a pas pu être sélectionné.",
		personalizeProfile: 'Personnaliser le profil',
		personalizeProfileDescription: 'Change son nom et sa photo sans toucher à sa progression.',
		profileName: 'Nom du profil',
		changePicture: 'Changer la photo',
		removePicture: 'Retirer la photo',
		profilePictureHint: 'PNG, JPEG ou WebP. Theia recadre et optimise automatiquement la photo.',
		profileSaveFailed: "Le profil n'a pas pu être enregistré.",
		savingProfile: 'Enregistrement…',
		saveProfile: 'Enregistrer le profil',
		back: 'Retour',
		settingsDescription: 'Préférences de cette application de lecture.',
		closeSettings: 'Fermer les réglages',
		interface: 'Interface',
		playback: 'Lecture',
		playbackHint: 'Comment le lecteur se comporte pendant un film.',
		settingsSections: 'Sections des réglages',
		language: 'Langue',
		languageHint: "Change uniquement la langue de l'application desktop.",
		autoHideControls: 'Masquer les contrôles',
		autoHideControlsHint: 'Fait disparaître le mobilier après trois secondes pendant la lecture.',
		reducedMotion: 'Réduire les animations',
		reducedMotionHint: 'Supprime les déplacements sans retirer les changements d’état utiles.',
		// What the playback sheet decides. The two slider numbers are pixels on
		// a picture 1080 tall, which is the unit the engine is given too: it is
		// converted once, in Rust, and the preview draws at the same proportion
		// so the two cannot drift apart.
		subtitles: 'Sous-titres',
		subtitlesHint: "Ces réglages s'appliquent à tous les films et à toutes les séries.",
		subtitlesReset: 'Tout réinitialiser',
		subtitlePreview: 'Aperçu',
		subtitlePreviewLine: 'Voilà à quoi ressembleront tes sous-titres.',
		subtitleSize: 'Taille du texte',
		subtitleSizeHint:
			'Le chiffre vaut pour une image de 1080 pixels de haut : sur une fenêtre plus petite, la taille suit la même proportion.',
		subtitleHeight: 'Hauteur',
		subtitleHeightHint:
			"Distance entre le bas de l'image et les sous-titres. Le minimum les garde au-dessus du bord, et le bandeau ne peut jamais sortir du cadre.",
		subtitleColour: 'Couleur du texte',
		subtitleColourHint:
			'Le jaune et le cyan sont les teintes historiques du sous-titrage : elles ressortent sur presque toutes les images.',
		subtitleOutline: 'Contour du texte',
		subtitleOutlineHint:
			"Ce qui détache les lettres de l'image. Le contour s'inverse automatiquement quand le texte est sombre.",
		outlineShadow: 'Ombre',
		outlineLine: 'Contour',
		outlineNone: 'Aucun',
		subtitleBand: 'Fond derrière le texte',
		subtitleBandHint:
			'Un bandeau derrière les sous-titres, comme à la télévision : la solution la plus lisible sur une image très claire. Il remplace le contour.',
		bandNone: 'Aucun fond',
		subtitleFont: 'Police',
		subtitleFontHint:
			'Standard est la police du système ; le serif et la chasse fixe sont deux autres familles, pour qui les préfère.',
		fontStandard: 'Standard',
		fontSerif: 'Serif',
		fontMono: 'Chasse fixe',
		subtitleBold: 'Gras',
		subtitleBoldHint: 'Un texte plus épais se lit mieux à distance, sur une télévision par exemple.',
		boldNormal: 'Normale',
		boldThick: 'Épaisse',
		autoPlayNext: "Lecture automatique de l'épisode suivant",
		autoPlayNextHint: "Lance l'épisode suivant quand celui-ci se termine, sans repasser par la bibliothèque.",
		audioLanguage: 'Langue audio par défaut',
		audioLanguageHint:
			"Auto garde la piste que le fichier annonce, VF préfère le français, VO suit la langue d'origine du titre. Le serveur la connaît pour les films, pas encore pour les séries : une série garde alors la piste par défaut du fichier.",
		audioAuto: 'Auto',
		audioVf: 'VF',
		audioVo: 'VO',
		subtitleLanguage: 'Sous-titres par défaut',
		subtitleLanguageHint:
			"Auto suit la piste que le fichier annonce, Aucun les garde éteints jusqu'à ce qu'on les demande dans le menu.",
		subtitleAuto: 'Auto',
		subtitleNone: 'Aucun',
		subtitleFr: 'FR',
		subtitleEn: 'EN',
		colourBone: 'Blanc cassé',
		colourWhite: 'Blanc',
		colourYellow: 'Jaune',
		colourCyan: 'Cyan',
		colourGold: 'Or',
		colourBlack: 'Noir',
		bandGrey: 'Gris',
		increase: 'Augmenter',
		decrease: 'Diminuer',
		pixels: 'px',
		server: 'Serveur',
		serverConnectedHint: 'Connexion locale active. Le player se reconnecte automatiquement au prochain lancement.',
		serverDisconnectedHint: "Aucun serveur n'est connecté.",
		copyAddress: "Copier l'adresse du serveur",
		addressCopied: 'Adresse copiée.',
		addressCopyFailed: "L'adresse n'a pas pu être copiée.",
		version: 'Version',
		update: 'Mise à jour',
		updateCurrent: 'Actuelle',
		updateLatest: 'Disponible',
		updateCheck: 'Vérifier',
		updateChecking: 'Vérification…',
		updateInstall: 'Installer la mise à jour',
		updateInstalling: 'Installation…',
		updateAvailable: 'Mise à jour disponible',
		updateReady: 'Mise à jour prête. Redémarre Theia pour terminer.',
		updateDeferred: 'La mise à jour attend que la lecture soit terminée.',
		updateFailed: "La mise à jour a échoué. Tu peux relancer la vérification.",
		updateUnsupported: "Les mises à jour automatiques ne sont pas disponibles sur cette installation.",
		updateUnknown: "Aucune vérification récente. Lance-en une maintenant.",
		// What was watched, in the settings sheet. The numbers are the server's
		// (decision 146): this pane prints them, including when they are zero,
		// because a section that hides an empty library reads as a broken one.
		overview: 'Vue d’ensemble',
		totalTime: 'Temps total',
		watchedEpisodes: 'Épisodes vus',
		completionRate: 'Taux de complétion',
		thisMonth: 'Ce mois',
		ratio: 'Ratio films / séries',
		watchedWord: 'visionné',
		countFilms: '{n} films',
		countFilmsOne: '1 film',
		countEpisodes: '{n} épisodes',
		countEpisodesOne: '1 épisode',
		watching: 'Visionnage',
		watchingHint:
			'Pour {who} : les heures comptent le temps réellement passé, pas la durée des fichiers. Un film est vu quand il en reste moins de deux minutes ou cinq pour cent ; une série quand tous ses épisodes le sont.',
		watchedMovies: 'Films vus',
		watchedSeries: 'Séries vues',
		topSeries: 'Séries les plus regardées',
		episodesOf: '{seen} sur {total} épisodes',
		episodesOfOne: '{seen} sur 1 épisode',
		nothingWatched: 'Aucune série n’a encore été regardée.',
		watchingUnavailable: 'Ce serveur ne rapporte pas encore ce qui a été regardé.',
		noTime: '—',
		cancel: 'Annuler',
		save: 'Enregistrer',
	},
	en: {
		play: 'Play',
		pause: 'Pause',
		back10: 'Back 10 seconds',
		forward10: 'Forward 10 seconds',
		mute: 'Mute',
		unmute: 'Unmute',
		volume: 'Volume',
		fullscreen: 'Full screen',
		exitFullscreen: 'Leave full screen',
		close: 'Close the player',
		minimize: 'Minimize the window',
		maximize: 'Maximize the window',
		restore: 'Restore the window',
		backToLibrary: 'Back to the library',
		tracks: 'Audio and subtitles',
		loading: 'Loading',
		engineUnavailable: 'The playback engine could not start, so no film can be opened.',
		engineUnavailableLabel: 'Playback',
		audioFallbackLabel: 'Sound',
		audioFallback:
			'The HDMI endpoint refused the raw audio stream, so the film is playing as decoded PCM. Nothing is broken, but the sound is not reaching the amplifier untouched.',

		chooseFilm: 'Choose a film',

		// The home screen - see the French catalogue's note on the {d}.
		home: 'Home',
		heroResumeEyebrow: 'You were watching',
		heroFeaturedEyebrow: 'Now showing',
		resume: 'Resume',
		remainingPattern: '{d} left',
		ratingScale: '/ 10',
		rowContinue: 'Continue watching',
		rowRecent: 'Recently added',
		rowTopRated: 'Top rated',
		rowTonight: 'Tonight’s random picks',
		rowTonightHint: 'A selection that changes every day',
		rowSeriesContinue: 'Continue a series',
		rowSeriesRecent: 'Recently added series',
		scrollLeft: 'Scroll left',
		scrollRight: 'Scroll right',
		homeFailed: 'The home screen could not be loaded.',

		connectTitle: 'Connect to Theia',
		starting: 'Starting Theia',
		startingHint: 'The server and library are getting ready…',
		library: 'Library',
		libraryNavigation: 'Library navigation',
		desktopPlayer: 'Desktop player',
		yourLibrary: 'Your library',
		films: 'Movies',
		allFilms: 'All movies',
		series: 'Series',
		search: 'Search',
		searchTitle: 'Search',
		searchPlaceholder: 'A movie, a series, a year…',
		searchHint: 'Start typing to explore the whole library.',
		noSearchResults: 'No title matches this search.',
		filmResults: 'Movies',
		seriesResults: 'Series',
		seriesLabel: 'Series',
		allSeries: 'All series',
		seasons: 'Seasons',
		season: 'Season',
		filmSingular: 'movie',
		filmPlural: 'movies',
		seriesSingular: 'series',
		seriesPlural: 'series',
		seasonSingular: 'season',
		seasonPlural: 'seasons',
		episodeSingular: 'episode',
		episodePlural: 'episodes',
		connected: 'Connected',
		playMovie: 'Play movie',
		openSeries: 'Open series',
		playEpisode: 'Play episode',
		episodeUntitled: 'Episode',
		address: 'Server address',
		connect: 'Connect',
		findServers: 'Find a server',
		searching: 'Searching…',
		noServer: 'No server answered on the network. Enter the address Theia prints when it starts.',
		connectionFailed: 'The connection failed. Check the address, and that Theia is running.',
		libraryFailed: 'The library could not be loaded.',
		seriesFailed: 'That series could not be loaded.',
		episodeFailed: 'That episode could not be opened.',
		playFailed: 'This film could not be opened.',
		stopFailed: 'The film could not be closed cleanly.',
		emptyLibrary: 'This library holds no films yet.',
		emptySeries: 'This library holds no series yet.',
		emptySeason: 'This season has no playable episode.',
		resumeAt: 'Resume at',
		audioTracks: 'Audio track',
		subtitleTracks: 'Subtitles',
		subtitlesOff: 'None',
		qualityTab: 'Quality',
		languagesTab: 'Languages',
		qualityOriginal: 'As the file is',
		trackFailed: 'That track could not be selected.',
		settings: 'Settings',
		profiles: 'Profiles',
		profileDescription: 'Choose who is watching. Library state and progress follow this profile.',
		closeProfiles: 'Close profiles',
		profileDefaultName: 'Main profile',
		currentProfile: 'Current profile',
		switchProfile: 'Use this profile',
		noProfiles: 'No profile is available on this server.',
		profileSwitchFailed: 'That profile could not be selected.',
		personalizeProfile: 'Customize profile',
		personalizeProfileDescription: 'Change its name and picture without touching its progress.',
		profileName: 'Profile name',
		changePicture: 'Change picture',
		removePicture: 'Remove picture',
		profilePictureHint: 'PNG, JPEG or WebP. Theia crops and optimizes the picture automatically.',
		profileSaveFailed: 'The profile could not be saved.',
		savingProfile: 'Saving…',
		saveProfile: 'Save profile',
		back: 'Back',
		settingsDescription: 'Preferences for this desktop player.',
		closeSettings: 'Close settings',
		interface: 'Interface',
		playback: 'Playback',
		playbackHint: 'How the player behaves while a film is playing.',
		settingsSections: 'Settings sections',
		language: 'Language',
		languageHint: 'Changes the language of this desktop app only.',
		autoHideControls: 'Hide controls',
		autoHideControlsHint: 'Hides the furniture after three seconds during playback.',
		reducedMotion: 'Reduce motion',
		reducedMotionHint: 'Removes movement without hiding useful state changes.',
		// What the playback sheet decides; see the French catalogue for the unit
		// the two slider numbers are in.
		subtitles: 'Subtitles',
		subtitlesHint: 'These settings apply to every film and every series.',
		subtitlesReset: 'Reset all',
		subtitlePreview: 'Preview',
		subtitlePreviewLine: 'This is how your subtitles will look.',
		subtitleSize: 'Text size',
		subtitleSizeHint:
			'The value is for a picture 1080 pixels tall: on a smaller window the size follows the same proportion.',
		subtitleHeight: 'Height',
		subtitleHeightHint:
			'Distance between the bottom of the picture and the subtitles. The minimum keeps them clear of the edge, and the band can never leave the frame.',
		subtitleColour: 'Text colour',
		subtitleColourHint:
			'Yellow and cyan are the historic subtitle tints: they stand out against almost any picture.',
		subtitleOutline: 'Text outline',
		subtitleOutlineHint:
			'What detaches the letters from the picture. The outline inverts by itself when the text is dark.',
		outlineShadow: 'Shadow',
		outlineLine: 'Outline',
		outlineNone: 'None',
		subtitleBand: 'Behind the text',
		subtitleBandHint:
			'A band behind the subtitles, like television: the most readable answer on a very bright picture. It replaces the outline.',
		bandNone: 'No band',
		subtitleFont: 'Font',
		subtitleFontHint:
			"Standard is the system's own font; serif and monospace are two other families, for whoever prefers them.",
		fontStandard: 'Standard',
		fontSerif: 'Serif',
		fontMono: 'Monospace',
		subtitleBold: 'Bold',
		subtitleBoldHint: 'Thicker text reads better at a distance, on a television for instance.',
		boldNormal: 'Normal',
		boldThick: 'Thick',
		autoPlayNext: 'Play the next episode automatically',
		autoPlayNextHint: 'Starts the next episode when this one ends, without going back to the library.',
		audioLanguage: 'Default audio language',
		audioLanguageHint:
			"Auto keeps the track the file announces, VF prefers French, VO follows the title's original language. The server knows it for films and not yet for series: a series keeps the file's own default track.",
		audioAuto: 'Auto',
		audioVf: 'VF',
		audioVo: 'VO',
		subtitleLanguage: 'Default subtitles',
		subtitleLanguageHint:
			'Auto follows the track the file announces, None keeps them off until they are asked for in the menu.',
		subtitleAuto: 'Auto',
		subtitleNone: 'None',
		subtitleFr: 'FR',
		subtitleEn: 'EN',
		colourBone: 'Off-white',
		colourWhite: 'White',
		colourYellow: 'Yellow',
		colourCyan: 'Cyan',
		colourGold: 'Gold',
		colourBlack: 'Black',
		bandGrey: 'Grey',
		increase: 'Increase',
		decrease: 'Decrease',
		pixels: 'px',
		server: 'Server',
		serverConnectedHint: 'Local connection active. The player reconnects automatically next time.',
		serverDisconnectedHint: 'No server is connected.',
		copyAddress: 'Copy the server address',
		addressCopied: 'Address copied.',
		addressCopyFailed: 'The address could not be copied.',
		version: 'Version',
		update: 'Update',
		updateCurrent: 'Current',
		updateLatest: 'Available',
		updateCheck: 'Check',
		updateChecking: 'Checking…',
		updateInstall: 'Install update',
		updateInstalling: 'Installing…',
		updateAvailable: 'Update available',
		updateReady: 'Update ready. Restart Theia to finish.',
		updateDeferred: 'The update is waiting for playback to finish.',
		updateFailed: 'The update failed. You can run the check again.',
		updateUnsupported: 'Automatic updates are not available for this installation.',
		updateUnknown: 'No recent check. Run one now.',
		// What was watched - see the French catalogue's note.
		overview: 'Overview',
		totalTime: 'Total time',
		watchedEpisodes: 'Episodes watched',
		completionRate: 'Completion rate',
		thisMonth: 'This month',
		ratio: 'Movies / series ratio',
		watchedWord: 'watched',
		countFilms: '{n} movies',
		countFilmsOne: '1 movie',
		countEpisodes: '{n} episodes',
		countEpisodesOne: '1 episode',
		watching: 'Viewing',
		watchingHint:
			'For {who}: hours count the time actually spent, not the length of what was watched. A film counts as watched under two minutes or five per cent from the end; a series when every episode does.',
		watchedMovies: 'Movies watched',
		watchedSeries: 'Series watched',
		topSeries: 'Most watched series',
		episodesOf: '{seen} of {total} episodes',
		episodesOfOne: '{seen} of 1 episode',
		nothingWatched: 'No series has been watched yet.',
		watchingUnavailable: 'This server does not report what has been watched yet.',
		noTime: '—',
		cancel: 'Cancel',
		save: 'Save',
	},
};

/** The words a track's label is built from, per language.
 *
 * The language names mirror the web application's own map, code for code, so a
 * track is called the same thing in both players; the channel words follow the
 * same rule ffmpeg does -- it writes "stereo" and "mono", and everything else
 * (5.1, 7.1, 3.0) already reads as itself. `channelCount` carries an {n} because
 * a container that writes no layout leaves only the number of channels, and
 * "6 canaux" is the honest thing to say about one. */
export const vocabulary = {
	fr: {
		languages: {
			fra: 'Français', fre: 'Français', fr: 'Français',
			eng: 'Anglais', en: 'Anglais',
			spa: 'Espagnol', es: 'Espagnol',
			deu: 'Allemand', ger: 'Allemand', de: 'Allemand',
			ita: 'Italien', it: 'Italien',
			por: 'Portugais', pt: 'Portugais',
			nld: 'Néerlandais', dut: 'Néerlandais', nl: 'Néerlandais',
			jpn: 'Japonais', ja: 'Japonais',
			zho: 'Chinois', chi: 'Chinois', zh: 'Chinois',
			kor: 'Coréen', ko: 'Coréen',
			rus: 'Russe', ru: 'Russe',
			ara: 'Arabe', ar: 'Arabe',
			pol: 'Polonais', pl: 'Polonais',
			swe: 'Suédois', sv: 'Suédois',
			dan: 'Danois', da: 'Danois',
			nor: 'Norvégien', no: 'Norvégien',
			fin: 'Finnois', fi: 'Finnois',
			tur: 'Turc', tr: 'Turc',
			ces: 'Tchèque', cze: 'Tchèque', cs: 'Tchèque',
			ell: 'Grec', gre: 'Grec', el: 'Grec',
			heb: 'Hébreu', he: 'Hébreu',
			hin: 'Hindi', hi: 'Hindi',
			und: 'Langue non précisée', mul: 'Multilingue',
		},
		channels: { mono: 'Mono', stereo: 'Stéréo' },
		channelCount: '{n} canaux',
		commentary: 'Commentaire',
		forced: 'Forcés',
		external: 'fichier joint',
		unnamedAudio: 'Piste {n}',
		unnamedSubtitle: 'Sous-titres {n}',
		qualityHeight: '{n}p',
		qualityReencoded: 'réencodée',
		qualityHardware: 'carte graphique',
		qualitySoftware: 'processeur',
		codecs: {
			ac3: 'AC-3', eac3: 'E-AC-3', dts: 'DTS', truehd: 'TrueHD', mlp: 'MLP',
			pcm: 'PCM', aac: 'AAC', flac: 'FLAC', alac: 'ALAC', opus: 'Opus', vorbis: 'Vorbis',
			mp3: 'MP3', mp2: 'MP2', wmav2: 'WMA', wmapro: 'WMA Pro',
			subrip: 'SubRip', ass: 'ASS', ssa: 'SSA', webvtt: 'WebVTT',
			hdmv_pgs_subtitle: 'PGS', dvd_subtitle: 'VobSub', dvdsub: 'VobSub',
			mov_text: 'Texte', ttml: 'TTML', dvb_subtitle: 'DVB',
		},
	},
	en: {
		languages: {
			fra: 'French', fre: 'French', fr: 'French',
			eng: 'English', en: 'English',
			spa: 'Spanish', es: 'Spanish',
			deu: 'German', ger: 'German', de: 'German',
			ita: 'Italian', it: 'Italian',
			por: 'Portuguese', pt: 'Portuguese',
			nld: 'Dutch', dut: 'Dutch', nl: 'Dutch',
			jpn: 'Japanese', ja: 'Japanese',
			zho: 'Chinese', chi: 'Chinese', zh: 'Chinese',
			kor: 'Korean', ko: 'Korean',
			rus: 'Russian', ru: 'Russian',
			ara: 'Arabic', ar: 'Arabic',
			pol: 'Polish', pl: 'Polish',
			swe: 'Swedish', sv: 'Swedish',
			dan: 'Danish', da: 'Danish',
			nor: 'Norwegian', no: 'Norwegian',
			fin: 'Finnish', fi: 'Finnish',
			tur: 'Turkish', tr: 'Turkish',
			ces: 'Czech', cze: 'Czech', cs: 'Czech',
			ell: 'Greek', gre: 'Greek', el: 'Greek',
			heb: 'Hebrew', he: 'Hebrew',
			hin: 'Hindi', hi: 'Hindi',
			und: 'Language not stated', mul: 'Multiple languages',
		},
		channels: { mono: 'Mono', stereo: 'Stereo' },
		channelCount: '{n} channels',
		commentary: 'Commentary',
		forced: 'Forced',
		external: 'external file',
		unnamedAudio: 'Track {n}',
		unnamedSubtitle: 'Subtitle {n}',
		qualityHeight: '{n}p',
		qualityReencoded: 're-encoded',
		qualityHardware: 'graphics card',
		qualitySoftware: 'processor',
		codecs: {
			ac3: 'AC-3', eac3: 'E-AC-3', dts: 'DTS', truehd: 'TrueHD', mlp: 'MLP',
			pcm: 'PCM', aac: 'AAC', flac: 'FLAC', alac: 'ALAC', opus: 'Opus', vorbis: 'Vorbis',
			mp3: 'MP3', mp2: 'MP2', wmav2: 'WMA', wmapro: 'WMA Pro',
			subrip: 'SubRip', ass: 'ASS', ssa: 'SSA', webvtt: 'WebVTT',
			hdmv_pgs_subtitle: 'PGS', dvd_subtitle: 'VobSub', dvdsub: 'VobSub',
			mov_text: 'Text', ttml: 'TTML', dvb_subtitle: 'DVB',
		},
	},
};

/** The vocabulary for a language, English when the code is not one of ours --
 * the same rule `initialLanguage` follows, because an unknown code must not be
 * able to empty a menu. */
export function trackVocabulary(language) {
	return vocabulary[language] ?? vocabulary.en;
}

/** The language this machine's viewer chose here, or null when nobody has.
 *
 * Kept apart from the language to open in, because the two answer different
 * questions: this one says whether the server's preference still has a say. */
export function storedLanguage() {
	try {
		const stored = localStorage.getItem('theia.player.language');
		if (stored && catalogues[stored]) return stored;
	} catch {
		// A WebView with storage disabled has no memory to read.
	}
	return null;
}

/** The interface language to open in: the stored choice wins, then the language
 * the installation was set up in arrives from the server (see App's connect),
 * and English is the base of the product — the player opens in English on every
 * machine until somebody picks another language, French systems included. */
export function initialLanguage() {
	return storedLanguage() ?? 'en';
}
