// The sitemap is a build-time endpoint rather than a public/ file: public/ is
// otherwise fully generated by sync-assets, and committing generated copies
// next to sources is the duplication liability decision 64 warns about.

import type { APIRoute } from 'astro';

const SITE = 'https://benitoow.github.io/theia-media';

export const GET: APIRoute = () =>
	new Response(
		`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>${SITE}/</loc>
	</url>
</urlset>
`,
		{ headers: { 'Content-Type': 'application/xml; charset=utf-8' } }
	);
